### ISSUE TITLE
Simple unitypackage integrated OpenIAB 

### ISSUE THREAD

**Issue by thaind** [Samsung-US-Developer-Support/Samsung-OpenIAB-Unity-Plugin#1]
Can you make a simple project integrated OpenIAB with SS IAP v3?
p/s: Apks demo worked fine on note4.

**Comment by Samsung-US-Developer-Support** [comment]
Hi thaind, 
We have the sample application project file available for download. The CityFlyer project is basically integrated Samsung IAP 3.0. 
You can get it from the Releases section: https://github.com/Samsung-US-Developer-Support/Samsung-OpenIAB-Unity-Plugin/releases 
Or get them from git by using lfs (they are big files). 

The integration guide basically uses the CityFlyer project to guide through the integration with Samsung IAP 3.0.
https://github.com/Samsung-US-Developer-Support/Samsung-OpenIAB-Unity-Plugin/blob/master/Samsung%20OpenIAB%20Unity%20Plugin%20Integration%20Guide%20for%20Samsung%20IAP%20-%20Android_v01.1.pdf

If you need additional information please let us know.

**Comment by thaind** [comment]
Nice document and example.
I will take a look.
Thank you so much.
